version: 2
jobs:
  review:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build Commands
        command: |
          pwd
          cd ..
          pwd
          git clone git@github.com:dev-sunbird/dev-sunbird.github.io.git site
          ls
          cd site
          chmod +x process.sh
          ./process.sh
          echo "baseurl: /pr/$CIRCLE_PR_NUMBER"/ >> _config.yml
          echo "buildVersion: PR - $CIRCLE_PR_NUMBER" >> _config.yml
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle exec jekyll build
          pwd
          ls
          aws s3 sync --delete --quiet _site/. s3://sunbird-trial/pr/$CIRCLE_PR_NUMBER
          prdata=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/dev-sunbird/docs/issues/$CIRCLE_PR_NUMBER)
          username=$(echo "${prdata}" | jq '.user.login')
          contributor=${username//\"/} 
          updatedfiles=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/dev-sunbird/docs/pulls/$CIRCLE_PR_NUMBER/files) 
          updatedfileslist=''
          for row in $(echo "${updatedfiles}" | jq -r '.[] | @base64')
          do  
           _jq() 
           {
            echo ${row} | base64 --decode | jq -r ${1}
           }
           file=$(_jq '.filename')
           echo $file
           if [[ "$file" == *"docs/"* ]] && [[ "$file" == *".md"* ]]
           then
           echo $file
           file=${file//\.md/}
           file=${file//index/}
           file=${file//.html/}
           file=${file//pages\//}
           url='- http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/'$file' <br /> '
           updatedfileslist=$updatedfileslist$url
           echo $url
           fi
          done 
          curl \
             -X POST \
             -u $guser:x-oauth-basic \
             -d '{"body": "Hello @'"$contributor"',<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'"$CIRCLE_PR_NUMBER"'. <br/> Modified pages are - <br />'"$updatedfileslist"' "}' \
             https://api.github.com/repos/dev-sunbird/docs/issues/$CIRCLE_PR_NUMBER/comments
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - review
