version: 2
jobs:
  pr:
    working_directory: /project/prdata/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build Commands
        command: |
          rm -rf site/
          branchdata=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/dev-sunbird/docs/pulls/$CIRCLE_PR_NUMBER)
          branchname=$(echo "${branchdata}" | jq '.base.ref')
          branchname=${branchname//\"/}
          echo "Branch Name is " $branchname
          cd ..
          git clone git@github.com:dev-sunbird/dev-sunbird.github.io.git site
          cd site
          chmod +x fetch.sh
          ./fetch.sh
          rm -rf docs/$branchname
          mkdir docs/$branchname
          cp -a ../prdata/. docs/$branchname
          rm -rf docs/$branchname/.git
          chmod +x version.sh
          ./version.sh
          echo "baseurl: /pr/$CIRCLE_PR_NUMBER"/ >> _config.yml
          echo "buildVersion: PR - $CIRCLE_PR_NUMBER" >> _config.yml
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete --quiet . s3://sunbird-trial/pr/$CIRCLE_PR_NUMBER
          prdata=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/dev-sunbird/docs/issues/$CIRCLE_PR_NUMBER)
          username=$(echo "${prdata}" | jq '.user.login')
          contributor=${username//\"/} 
          updatedfiles=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/dev-sunbird/docs/pulls/$CIRCLE_PR_NUMBER/files) 
          updatedfileslist=''
          updatedsectionslist=''
          for row in $(echo "${updatedfiles}" | jq -r '.[] | @base64')
           do  
            _jq() 
            {
             echo ${row} | base64 --decode | jq -r ${1}
            }
            file=$(_jq '.filename')
            echo $file
            
            if [[ "$file" != ingredients/* ]] && [[ "$file" == *.md ]]
            then
            filedocs=${file//\.md/}
            filedocs=${filedocs//index/}
            url='- http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/docs/'$branchname'/'$filedocs' <br /> '
            updatedfileslist=$updatedfileslist$url
            echo $url
            fi
            
            if [[ "$file" == apis/* ]] && [[ "$file" == *.yaml ]]
            then
            filelastsegment=${file##*/}
            echo $filelastsegment
            fileapi=${filelastsegment//.yaml/}
            url='- http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/docs/'$branchname'/apis/specs/?api='$fileapi' <br /> '
            updatedfileslist=$updatedfileslist$url
            echo $url
            fi
            
            if [[ "$file" == apis/* ]] && [[ "$file" == *.html ]]
            then
            filedocs=${file//\.html/}
            filedocs=${filedocs//index/}
            echo $filelastsegment
            url='- http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/docs/'$branchname'/apis/specs/ <br /> '
            updatedfileslist=$updatedfileslist$url
            echo $url
            fi
            
            if [[ "$file" == version.yaml ]]
            then
            url='- http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/docs/'$branchname'/ <br/> - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'$CIRCLE_PR_NUMBER'/docs/ <br/>  - Sidebar on Docs Pages'
            updatedsectionslist=$updatedsectionslist$url
            fi
            
           done 
          curl \
             -X POST \
             -u $guser:x-oauth-basic \
             -d '{"body": "Hello @'"$contributor"',<br/><br/> _This is a auto-generated response._ <br/><br/> Click the URL for review pull request - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/pr/'"$CIRCLE_PR_NUMBER"'. <br/><br/> **Modified pages are -** <br />'"$updatedfileslist"' <br/> **Modified sections are -** <br />'"$updatedsectionslist"' "}' \
              https://api.github.com/repos/dev-sunbird/docs/issues/$CIRCLE_PR_NUMBER/comments
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - pr
